In [1]:
import pandas as pd
import pathlib

Select out the data I want from the BMI dataset.

In [2]:
datasets_path = pathlib.Path.cwd()/'Datasets'

In [4]:
BMI = pd.read_csv(datasets_path/'NCD_BMI_30A.csv')
BMI

,Unnamed: 0,2016,2016.1,2016.2,2015,2015.1,2015.2,2014,2014.1,2014.2,...,1978.2,1977,1977.1,1977.2,1976,1976.1,1976.2,1975,1975.1,1975.2
0,NaN,"Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...",...,"Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;..."
1,NaN,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,...,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years
2,Country,Both sexes,Male,Female,Both sexes,Male,Female,Both sexes,Male,Female,...,Female,Both sexes,Male,Female,Both sexes,Male,Female,Both sexes,Male,Female
3,Afghanistan,5.5 [3.4-8.1],3.2 [1.3-6.4],7.6 [4.3-12.4],5.2 [3.3-7.7],3.0 [1.3-6.0],7.3 [4.1-11.8],4.9 [3.1-7.3],2.8 [1.2-5.6],7.0 [4.0-11.3],...,0.9 [0.3-2.2],0.6 [0.2-1.2],0.2 [0.0-0.7],0.9 [0.3-2.1],0.5 [0.2-1.1],0.2 [0.0-0.7],0.8 [0.2-2.0],0.5 [0.2-1.1],0.2 [0.0-0.6],0.8 [0.2-2.0]
4,Albania,21.7 [17.0-26.7],21.6 [14.8-29.0],21.8 [15.3-28.9],21.1 [16.6-26.0],20.9 [14.4-28.1],21.3 [15.1-28.1],20.5 [16.2-25.1],20.2 [13.9-27.3],20.8 [14.9-27.4],...,9.1 [4.6-15.5],6.8 [4.0-10.7],4.8 [2.0-9.3],8.9 [4.3-15.4],6.7 [3.8-10.6],4.6 [1.8-9.2],8.8 [4.1-15.4],6.5 [3.6-10.5],4.4 [1.7-9.2],8.6 [3.9-15.4]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,Venezuela (Bolivarian Republic of),25.6 [21.3-30.2],22.4 [16.4-28.9],28.6 [22.5-35.2],25.2 [21.0-29.5],22.0 [16.2-28.2],28.3 [22.4-34.6],24.8 [20.8-29.0],21.5 [16.0-27.4],27.9 [22.2-34.1],...,14.4 [8.4-21.4],10.3 [6.7-14.6],6.6 [3.2-11.7],14.0 [8.0-21.3],9.9 [6.3-14.3],6.3 [2.9-11.5],13.6 [7.5-21.0],9.6 [5.9-14.1],5.9 [2.7-11.2],13.2 [7.1-20.7]
194,Viet Nam,2.1 [1.4-3.1],1.6 [0.8-2.8],2.6 [1.5-4.2],2.0 [1.3-2.9],1.5 [0.8-2.5],2.4 [1.4-3.9],1.8 [1.2-2.6],1.3 [0.7-2.3],2.3 [1.3-3.6],...,0.2 [0.1-0.6],0.2 [0.1-0.3],0.1 [0.0-0.2],0.2 [0.1-0.5],0.1 [0.1-0.3],0.1 [0.0-0.2],0.2 [0.1-0.5],0.1 [0.0-0.3],0.1 [0.0-0.2],0.2 [0.1-0.5]
195,Yemen,17.1 [13.3-21.3],12.0 [7.3-17.6],22.0 [16.0-28.4],16.5 [12.9-20.5],11.4 [7.0-16.7],21.3 [15.6-27.4],15.9 [12.4-19.6],10.8 [6.7-15.7],20.6 [15.2-26.4],...,4.8 [2.0-9.3],3.1 [1.5-5.7],1.3 [0.4-3.3],4.5 [1.9-9.2],2.9 [1.4-5.6],1.3 [0.3-3.2],4.3 [1.7-9.0],2.8 [1.3-5.4],1.2 [0.3-3.1],4.2 [1.5-8.9]
196,Zambia,8.1 [5.8-10.7],3.6 [1.7-6.5],12.4 [8.5-17.1],7.7 [5.6-10.2],3.4 [1.6-6.1],12.0 [8.2-16.4],7.4 [5.4-9.8],3.2 [1.5-5.7],11.5 [7.9-15.7],...,3.0 [1.3-5.6],1.7 [0.8-3.2],0.5 [0.1-1.5],2.9 [1.2-5.4],1.6 [0.7-3.1],0.5 [0.1-1.4],2.7 [1.1-5.3],1.5 [0.7-3.0],0.5 [0.1-1.4],2.5 [1.0-5.1]
197,Zimbabwe,15.5 [12.0-19.2],4.7 [2.5-8.0],25.3 [19.1-32.0],15.2 [11.9-18.8],4.5 [2.4-7.6],24.8 [18.9-31.3],14.9 [11.7-18.4],4.4 [2.4-7.3],24.4 [18.8-30.6],...,7.7 [3.9-13.1],4.0 [2.1-6.8],0.5 [0.1-1.3],7.4 [3.6-12.7],3.9 [1.9-6.7],0.5 [0.1-1.3],7.0 [3.3-12.4],3.7 [1.7-6.5],0.4 [0.1-1.3],6.7 [3.0-12.2]

In [16]:
BMI_2015_messy = BMI[['Unnamed: 0', '2015']]
BMI_2015_messy

,Unnamed: 0,2015
0,NaN,"Prevalence of obesity among adults, BMI &amp;..."
1,NaN,18+ years
2,Country,Both sexes
3,Afghanistan,5.2 [3.3-7.7]
4,Albania,21.1 [16.6-26.0]
...,...,...
193,Venezuela (Bolivarian Republic of),25.2 [21.0-29.5]
194,Viet Nam,2.0 [1.3-2.9]
195,Yemen,16.5 [12.9-20.5]
196,Zambia,7.7 [5.6-10.2]
197,Zimbabwe,15.2 [11.9-18.8]

In [17]:
BMI_2015 = BMI_2015_messy.drop(BMI_2015_messy.index[0:3])
BMI_2015

                             Unnamed: 0              2015
3                           Afghanistan     5.2 [3.3-7.7]
4                               Albania  21.1 [16.6-26.0]
5                               Algeria  26.7 [21.9-31.8]
6                               Andorra  25.4 [20.1-31.0]
7                                Angola    7.9 [4.9-11.7]
..                                  ...               ...
193  Venezuela (Bolivarian Republic of)  25.2 [21.0-29.5]
194                            Viet Nam     2.0 [1.3-2.9]
195                               Yemen  16.5 [12.9-20.5]
196                              Zambia    7.7 [5.6-10.2]
197                            Zimbabwe  15.2 [11.9-18.8]

[195 rows x 2 columns]

In [23]:
BMI_2015.columns = ['Location', 'BMI30Plus']
BMI_2015

                               Location         BMI30Plus
3                           Afghanistan     5.2 [3.3-7.7]
4                               Albania  21.1 [16.6-26.0]
5                               Algeria  26.7 [21.9-31.8]
6                               Andorra  25.4 [20.1-31.0]
7                                Angola    7.9 [4.9-11.7]
..                                  ...               ...
193  Venezuela (Bolivarian Republic of)  25.2 [21.0-29.5]
194                            Viet Nam     2.0 [1.3-2.9]
195                               Yemen  16.5 [12.9-20.5]
196                              Zambia    7.7 [5.6-10.2]
197                            Zimbabwe  15.2 [11.9-18.8]

[195 rows x 2 columns]

# Combine Data

In [19]:
training = pd.read_csv('training_small_cleaner_with_tobacco.csv')
training

,Location,NTDs,Poisoning,Tobacco,Tuberculosis,Under5Mortality,DrinkingWater,Alcohol,BasicSanitization,CancerEtc,HALE,InfantMortality,LifeExpectancy,MaternalMortality,NeonatalMortality
0,Afghanistan,13765392,1.22,NaN,189.0,70.44,52.39,0.210,40.71,29.8,52.60,53.17,61.65,701.0,40.27
1,Albania,16,0.43,29.9,17.0,9.57,89.88,6.740,97.69,17.4,69.03,8.51,77.84,15.0,6.03
2,Algeria,7561,0.80,19.3,75.0,25.18,88.69,0.930,87.50,14.4,65.99,21.61,76.54,114.0,15.05
3,Andorra,0,NaN,34.2,5.9,3.53,100.00,11.010,100.00,NaN,NaN,3.34,NaN,NaN,1.71
4,Angola,18534219,2.95,NaN,366.0,88.20,26.71,7.960,47.37,16.9,53.66,57.82,61.72,251.0,30.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Venezuela (Bolivarian Republic of),280243,0.30,NaN,30.0,NaN,95.83,6.820,93.94,18.2,65.10,NaN,74.66,115.0,14.45
190,Viet Nam,4468764,0.93,NaN,199.0,NaN,90.73,7.860,80.08,17.3,64.89,NaN,73.16,45.0,11.37
191,Yemen,5840695,3.74,22.2,48.0,NaN,54.70,0.055,58.50,30.7,58.38,NaN,67.47,169.0,26.65
192,Zambia,11830416,3.06,15.4,391.0,NaN,40.59,6.890,25.98,18.0,52.71,NaN,60.50,232.0,24.53
193,Zimbabwe,10346543,2.37,14.5,242.0,NaN,51.03,4.920,37.57,19.4,51.17,NaN,58.48,480.0,27.89

In [24]:
training_BMI = pd.merge(training, BMI_2015, on = "Location", how = "left")

In [25]:
training_BMI

,Location,NTDs,Poisoning,Tobacco,Tuberculosis,Under5Mortality,DrinkingWater,Alcohol,BasicSanitization,CancerEtc,HALE,InfantMortality,LifeExpectancy,MaternalMortality,NeonatalMortality,BMI30Plus
0,Afghanistan,13765392,1.22,NaN,189.0,70.44,52.39,0.210,40.71,29.8,52.60,53.17,61.65,701.0,40.27,5.2 [3.3-7.7]
1,Albania,16,0.43,29.9,17.0,9.57,89.88,6.740,97.69,17.4,69.03,8.51,77.84,15.0,6.03,21.1 [16.6-26.0]
2,Algeria,7561,0.80,19.3,75.0,25.18,88.69,0.930,87.50,14.4,65.99,21.61,76.54,114.0,15.05,26.7 [21.9-31.8]
3,Andorra,0,NaN,34.2,5.9,3.53,100.00,11.010,100.00,NaN,NaN,3.34,NaN,NaN,1.71,25.4 [20.1-31.0]
4,Angola,18534219,2.95,NaN,366.0,88.20,26.71,7.960,47.37,16.9,53.66,57.82,61.72,251.0,30.63,7.9 [4.9-11.7]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Venezuela (Bolivarian Republic of),280243,0.30,NaN,30.0,NaN,95.83,6.820,93.94,18.2,65.10,NaN,74.66,115.0,14.45,25.2 [21.0-29.5]
190,Viet Nam,4468764,0.93,NaN,199.0,NaN,90.73,7.860,80.08,17.3,64.89,NaN,73.16,45.0,11.37,2.0 [1.3-2.9]
191,Yemen,5840695,3.74,22.2,48.0,NaN,54.70,0.055,58.50,30.7,58.38,NaN,67.47,169.0,26.65,16.5 [12.9-20.5]
192,Zambia,11830416,3.06,15.4,391.0,NaN,40.59,6.890,25.98,18.0,52.71,NaN,60.50,232.0,24.53,7.7 [5.6-10.2]
193,Zimbabwe,10346543,2.37,14.5,242.0,NaN,51.03,4.920,37.57,19.4,51.17,NaN,58.48,480.0,27.89,15.2 [11.9-18.8]

In [26]:
training_BMI.to_csv('training_small_cleaner_with_tobacco_BMI.csv', index = False)