In [1]:
import pandas as pd
import pathlib

Select out the data I want from the BMI dataset.

In [2]:
datasets_path = pathlib.Path.cwd()/'Datasets'

In [3]:
BMI = pd.read_csv(datasets_path/'NCD_BMI_30A.csv')
BMI

,Unnamed: 0,2016,2016.1,2016.2,2015,2015.1,2015.2,2014,2014.1,2014.2,...,1978.2,1977,1977.1,1977.2,1976,1976.1,1976.2,1975,1975.1,1975.2
0,NaN,"Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...",...,"Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;...","Prevalence of obesity among adults, BMI &amp;..."
1,NaN,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,...,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years,18+ years
2,Country,Both sexes,Male,Female,Both sexes,Male,Female,Both sexes,Male,Female,...,Female,Both sexes,Male,Female,Both sexes,Male,Female,Both sexes,Male,Female
3,Afghanistan,5.5 [3.4-8.1],3.2 [1.3-6.4],7.6 [4.3-12.4],5.2 [3.3-7.7],3.0 [1.3-6.0],7.3 [4.1-11.8],4.9 [3.1-7.3],2.8 [1.2-5.6],7.0 [4.0-11.3],...,0.9 [0.3-2.2],0.6 [0.2-1.2],0.2 [0.0-0.7],0.9 [0.3-2.1],0.5 [0.2-1.1],0.2 [0.0-0.7],0.8 [0.2-2.0],0.5 [0.2-1.1],0.2 [0.0-0.6],0.8 [0.2-2.0]
4,Albania,21.7 [17.0-26.7],21.6 [14.8-29.0],21.8 [15.3-28.9],21.1 [16.6-26.0],20.9 [14.4-28.1],21.3 [15.1-28.1],20.5 [16.2-25.1],20.2 [13.9-27.3],20.8 [14.9-27.4],...,9.1 [4.6-15.5],6.8 [4.0-10.7],4.8 [2.0-9.3],8.9 [4.3-15.4],6.7 [3.8-10.6],4.6 [1.8-9.2],8.8 [4.1-15.4],6.5 [3.6-10.5],4.4 [1.7-9.2],8.6 [3.9-15.4]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,Venezuela (Bolivarian Republic of),25.6 [21.3-30.2],22.4 [16.4-28.9],28.6 [22.5-35.2],25.2 [21.0-29.5],22.0 [16.2-28.2],28.3 [22.4-34.6],24.8 [20.8-29.0],21.5 [16.0-27.4],27.9 [22.2-34.1],...,14.4 [8.4-21.4],10.3 [6.7-14.6],6.6 [3.2-11.7],14.0 [8.0-21.3],9.9 [6.3-14.3],6.3 [2.9-11.5],13.6 [7.5-21.0],9.6 [5.9-14.1],5.9 [2.7-11.2],13.2 [7.1-20.7]
194,Viet Nam,2.1 [1.4-3.1],1.6 [0.8-2.8],2.6 [1.5-4.2],2.0 [1.3-2.9],1.5 [0.8-2.5],2.4 [1.4-3.9],1.8 [1.2-2.6],1.3 [0.7-2.3],2.3 [1.3-3.6],...,0.2 [0.1-0.6],0.2 [0.1-0.3],0.1 [0.0-0.2],0.2 [0.1-0.5],0.1 [0.1-0.3],0.1 [0.0-0.2],0.2 [0.1-0.5],0.1 [0.0-0.3],0.1 [0.0-0.2],0.2 [0.1-0.5]
195,Yemen,17.1 [13.3-21.3],12.0 [7.3-17.6],22.0 [16.0-28.4],16.5 [12.9-20.5],11.4 [7.0-16.7],21.3 [15.6-27.4],15.9 [12.4-19.6],10.8 [6.7-15.7],20.6 [15.2-26.4],...,4.8 [2.0-9.3],3.1 [1.5-5.7],1.3 [0.4-3.3],4.5 [1.9-9.2],2.9 [1.4-5.6],1.3 [0.3-3.2],4.3 [1.7-9.0],2.8 [1.3-5.4],1.2 [0.3-3.1],4.2 [1.5-8.9]
196,Zambia,8.1 [5.8-10.7],3.6 [1.7-6.5],12.4 [8.5-17.1],7.7 [5.6-10.2],3.4 [1.6-6.1],12.0 [8.2-16.4],7.4 [5.4-9.8],3.2 [1.5-5.7],11.5 [7.9-15.7],...,3.0 [1.3-5.6],1.7 [0.8-3.2],0.5 [0.1-1.5],2.9 [1.2-5.4],1.6 [0.7-3.1],0.5 [0.1-1.4],2.7 [1.1-5.3],1.5 [0.7-3.0],0.5 [0.1-1.4],2.5 [1.0-5.1]
197,Zimbabwe,15.5 [12.0-19.2],4.7 [2.5-8.0],25.3 [19.1-32.0],15.2 [11.9-18.8],4.5 [2.4-7.6],24.8 [18.9-31.3],14.9 [11.7-18.4],4.4 [2.4-7.3],24.4 [18.8-30.6],...,7.7 [3.9-13.1],4.0 [2.1-6.8],0.5 [0.1-1.3],7.4 [3.6-12.7],3.9 [1.9-6.7],0.5 [0.1-1.3],7.0 [3.3-12.4],3.7 [1.7-6.5],0.4 [0.1-1.3],6.7 [3.0-12.2]

In [4]:
BMI_2016_messy = BMI[['Unnamed: 0', '2016']]
BMI_2016_messy

,Unnamed: 0,2016
0,NaN,"Prevalence of obesity among adults, BMI &amp;..."
1,NaN,18+ years
2,Country,Both sexes
3,Afghanistan,5.5 [3.4-8.1]
4,Albania,21.7 [17.0-26.7]
...,...,...
193,Venezuela (Bolivarian Republic of),25.6 [21.3-30.2]
194,Viet Nam,2.1 [1.4-3.1]
195,Yemen,17.1 [13.3-21.3]
196,Zambia,8.1 [5.8-10.7]
197,Zimbabwe,15.5 [12.0-19.2]

In [5]:
BMI_2016 = BMI_2016_messy.drop(BMI_2016_messy.index[0:3])
BMI_2016

                             Unnamed: 0              2016
3                           Afghanistan     5.5 [3.4-8.1]
4                               Albania  21.7 [17.0-26.7]
5                               Algeria  27.4 [22.5-32.7]
6                               Andorra  25.6 [20.1-31.3]
7                                Angola    8.2 [5.1-12.2]
..                                  ...               ...
193  Venezuela (Bolivarian Republic of)  25.6 [21.3-30.2]
194                            Viet Nam     2.1 [1.4-3.1]
195                               Yemen  17.1 [13.3-21.3]
196                              Zambia    8.1 [5.8-10.7]
197                            Zimbabwe  15.5 [12.0-19.2]

[195 rows x 2 columns]

In [6]:
BMI_2016.columns = ['Location', 'BMI30Plus']
BMI_2016

                               Location         BMI30Plus
3                           Afghanistan     5.5 [3.4-8.1]
4                               Albania  21.7 [17.0-26.7]
5                               Algeria  27.4 [22.5-32.7]
6                               Andorra  25.6 [20.1-31.3]
7                                Angola    8.2 [5.1-12.2]
..                                  ...               ...
193  Venezuela (Bolivarian Republic of)  25.6 [21.3-30.2]
194                            Viet Nam     2.1 [1.4-3.1]
195                               Yemen  17.1 [13.3-21.3]
196                              Zambia    8.1 [5.8-10.7]
197                            Zimbabwe  15.5 [12.0-19.2]

[195 rows x 2 columns]

## Combine Data

In [7]:
test = pd.read_csv('test_small_cleaner_with_tobacco.csv')
test

,Location,NTDs,Poisoning,Tuberculosis,Under5Mortality,DrinkingWater,Alcohol,BasicSanitization,CancerEtc,HALE,InfantMortality,LifeExpectancy,MaternalMortality,NeonatalMortality,Tobacco
0,Afghanistan,13275429,1.19,189.0,67.57,54.84,0.210,42.05,29.8,53.95,51.32,63.21,673.0,39.05,NaN
1,Albania,21,0.44,17.0,9.42,89.88,7.170,97.70,17.0,69.08,8.38,78.00,16.0,6.33,29.7
2,Algeria,10752,0.77,70.0,24.79,88.69,0.950,87.54,14.2,66.39,21.28,77.13,113.0,15.07,19.1
3,Andorra,0,NaN,6.0,3.37,100.00,11.020,100.00,NaN,NaN,3.20,NaN,NaN,1.63,33.9
4,Angola,14419092,2.70,362.0,84.21,27.08,6.940,48.63,16.5,54.84,55.56,63.06,246.0,29.78,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Venezuela (Bolivarian Republic of),282294,0.29,34.0,NaN,95.78,4.140,93.94,18.1,64.44,NaN,73.95,121.0,14.62,NaN
190,Viet Nam,6953978,0.92,193.0,NaN,91.68,8.660,81.86,17.1,65.30,NaN,73.74,44.0,11.19,NaN
191,Yemen,5985649,3.77,48.0,NaN,54.70,0.051,58.77,30.6,57.53,NaN,66.63,165.0,26.62,21.7
192,Zambia,11573334,2.94,376.0,NaN,41.18,6.540,26.09,17.9,54.40,NaN,62.45,222.0,24.25,15.2
193,Zimbabwe,9958235,2.23,233.0,NaN,50.42,4.670,36.89,19.3,53.07,NaN,60.68,468.0,27.33,14.3

In [9]:
test_BMI = pd.merge(test, BMI_2016, on = "Location", how = "left")

In [10]:
test_BMI

,Location,NTDs,Poisoning,Tuberculosis,Under5Mortality,DrinkingWater,Alcohol,BasicSanitization,CancerEtc,HALE,InfantMortality,LifeExpectancy,MaternalMortality,NeonatalMortality,Tobacco,BMI30Plus
0,Afghanistan,13275429,1.19,189.0,67.57,54.84,0.210,42.05,29.8,53.95,51.32,63.21,673.0,39.05,NaN,5.5 [3.4-8.1]
1,Albania,21,0.44,17.0,9.42,89.88,7.170,97.70,17.0,69.08,8.38,78.00,16.0,6.33,29.7,21.7 [17.0-26.7]
2,Algeria,10752,0.77,70.0,24.79,88.69,0.950,87.54,14.2,66.39,21.28,77.13,113.0,15.07,19.1,27.4 [22.5-32.7]
3,Andorra,0,NaN,6.0,3.37,100.00,11.020,100.00,NaN,NaN,3.20,NaN,NaN,1.63,33.9,25.6 [20.1-31.3]
4,Angola,14419092,2.70,362.0,84.21,27.08,6.940,48.63,16.5,54.84,55.56,63.06,246.0,29.78,NaN,8.2 [5.1-12.2]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Venezuela (Bolivarian Republic of),282294,0.29,34.0,NaN,95.78,4.140,93.94,18.1,64.44,NaN,73.95,121.0,14.62,NaN,25.6 [21.3-30.2]
190,Viet Nam,6953978,0.92,193.0,NaN,91.68,8.660,81.86,17.1,65.30,NaN,73.74,44.0,11.19,NaN,2.1 [1.4-3.1]
191,Yemen,5985649,3.77,48.0,NaN,54.70,0.051,58.77,30.6,57.53,NaN,66.63,165.0,26.62,21.7,17.1 [13.3-21.3]
192,Zambia,11573334,2.94,376.0,NaN,41.18,6.540,26.09,17.9,54.40,NaN,62.45,222.0,24.25,15.2,8.1 [5.8-10.7]
193,Zimbabwe,9958235,2.23,233.0,NaN,50.42,4.670,36.89,19.3,53.07,NaN,60.68,468.0,27.33,14.3,15.5 [12.0-19.2]

In [11]:
test_BMI.to_csv('test_small_messy_with_tobacco_BMI.csv', index = False)